// Static content shared by the no-credentials home view AND the generated
// SKILL.md (AXI principle 7). Both must work with zero network access, so
// nothing here calls the GoHighLevel API - the live, credentialed home view
// lives in src/commands/home.ts instead. Edit here; skills/gohighlevel-axi/SKILL.md
// is regenerated by `npm run skill:gen` and CI fails if it drifts
// (`npm run skill:check`).

import { homedir } from "node:os";
import { emitList } from "../output/toon.js";
import { helpBlock } from "../output/suggest.js";

export const DESCRIPTION =
  "Agent CLI for GoHighLevel (LeadConnector): contacts, conversations, calendars, opportunities, payments, and workflows - every send, trigger, charge, or delete defaults to a dry-run and requires --confirm";

export const SPEC_VERSION = "axi/1.0-2026-07";

export function collapseHome(path: string): string {
  const home = homedir();
  return path.startsWith(home) ? "~" + path.slice(home.length) : path;
}

/** Top-level read commands shown in the compact, no-credentials home view. */
const TOP_LEVEL_COMMANDS = [
  { command: "contacts", summary: "List/search contacts" },
  { command: "conversations", summary: "List conversation threads" },
  { command: "calendars", summary: "List calendars" },
  { command: "appointments", summary: "List appointments" },
  { command: "pipelines", summary: "List pipelines and stages" },
  { command: "opportunities", summary: "List opportunities" },
  { command: "payments", summary: "List payment orders (read-only)" },
  { command: "subscriptions", summary: "List subscriptions (read-only)" },
  { command: "workflows", summary: "List workflows" },
  { command: "webhooks", summary: "Webhook subscription support status" },
];

/** Every registered command, for `--help` and SKILL.md (AXI principle 10). */
const ALL_COMMANDS = [
  ...TOP_LEVEL_COMMANDS.filter((c) => c.command !== "webhooks"),
  { command: "contact <id>", summary: "Show contact detail" },
  { command: "contact add", summary: "Create a contact (gated, --confirm)" },
  { command: "contact rm <id>", summary: "Delete a contact (gated, --confirm)" },
  { command: "contact update <id>", summary: "Update contact fields" },
  { command: "conversation <id>", summary: "Conversation detail + recent messages" },
  { command: "message send", summary: "Send SMS/Email to a contact (gated, --confirm)" },
  { command: "calendar <id>", summary: "Show calendar detail" },
  { command: "appointment <id>", summary: "Show appointment detail" },
  { command: "appointment book", summary: "Book an appointment (gated, --confirm)" },
  { command: "appointment cancel <id>", summary: "Cancel an appointment (gated, --confirm)" },
  { command: "pipeline <id>", summary: "Show one pipeline's stages" },
  { command: "opportunity <id>", summary: "Show opportunity detail" },
  { command: "opportunity move <id>", summary: "Move an opportunity to a new stage (gated, --confirm)" },
  { command: "payment <id>", summary: "Show payment order detail" },
  { command: "payment record <id>", summary: "Record a payment against an order (gated, --confirm - highest stakes)" },
  { command: "workflow trigger <id>", summary: "Enroll a contact in a workflow (gated, --confirm)" },
  { command: "webhooks", summary: "Explain webhook subscription limitations" },
  { command: "webhooks add <url>", summary: "Not supported (no runtime webhook API exists)" },
  { command: "webhooks rm <id>", summary: "Not supported (no runtime webhook API exists)" },
];

/** The compact, static, no-network command overview (AXI principle 8). */
export function homeBody(tool: string): string {
  const table = emitList(
    "commands",
    TOP_LEVEL_COMMANDS.map((c) => ({ ...c })),
    ["command", "summary"],
  );
  const help = helpBlock([
    `${tool} --help`,
    `${tool} contacts --query <text>`,
  ]);
  return [table, help].join("\n");
}

export function homeHeader(binPath: string): string {
  return `gohighlevel-axi: ${collapseHome(binPath)} - ${DESCRIPTION}`;
}

/** Full tool reference for `gohighlevel-axi --help`. */
export function rootHelpText(): string {
  const commands = emitList(
    "commands",
    ALL_COMMANDS.map((c) => ({ ...c })),
    ["command", "summary"],
  );
  const flags = emitList(
    "flags",
    [
      { flag: "--help", default: "", description: "show help for any command" },
      { flag: "--version", default: "", description: "print the tool version" },
      { flag: "--confirm", default: "", description: "execute a gated (send/trigger/charge/delete) command instead of dry-running it" },
    ],
    ["flag", "default", "description"],
  );
  return [
    `gohighlevel-axi: ${DESCRIPTION}`,
    commands,
    flags,
    "env[2]{name,description}:",
    "  GHL_API_KEY,GoHighLevel Private Integration Token (Bearer auth)",
    "  GHL_LOCATION_ID,sub-account (location) id most endpoints require",
    "examples[3]:",
    "  gohighlevel-axi contacts --query jane",
    "  gohighlevel-axi contact add --first-name Jane --last-name Doe --email jane@example.com --confirm",
    "  gohighlevel-axi message send --contact abc123 --body \"hi\" --confirm",
  ].join("\n");
}

/** The static SKILL.md: home content with zero-install command forms. */
export function renderSkill(): string {
  const frontmatter = [
    "---",
    "name: gohighlevel-axi",
    `description: "${DESCRIPTION.replace(/"/g, "'")}"`,
    "---",
  ].join("\n");
  const commands = emitList(
    "commands",
    ALL_COMMANDS.map((c) => ({ ...c })),
    ["command", "summary"],
  );
  const body = [
    "# gohighlevel-axi",
    "",
    `${DESCRIPTION} (built against AXI spec ${SPEC_VERSION}). Run the commands below with npx - no install needed.`,
    "",
    "## Setup",
    "",
    "Set `GHL_API_KEY` to a GoHighLevel Private Integration Token (Settings -> Private Integrations in the target sub-account) and `GHL_LOCATION_ID` to that sub-account's location id. Both may instead be written to `~/.config/gohighlevel-axi/credentials` as `token = ...` / `location_id = ...`.",
    "",
    "## Safety model",
    "",
    "Every command that sends a message, triggers a workflow, records a payment, books/cancels an appointment, moves an opportunity's stage, or creates/deletes a contact defaults to a **dry-run**: it prints the exact method, endpoint, and payload it would send, and makes **no network call**. Re-run the identical command with `--confirm` appended to actually execute it. There is no bare/no-flag way to trigger any of these effects. Read-only commands (list/get) are never gated.",
    "",
    "## Commands",
    "",
    "```",
    commands,
    "```",
    "",
    "Every command supports `--help`. Exit codes: 0 success/no-op, 1 error, 2 usage error. All output is TOON on stdout.",
  ].join("\n");
  return [frontmatter, "", body, ""].join("\n");
}
